build: project_runner.sh updated to return result to docker container

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -60,4 +60,9 @@ jobs:
           -e NEXT_PUBLIC_S3_BUCKET=${{ secrets.NEXT_PUBLIC_S3_BUCKET }} \
           -v "$(pwd)":/app -d --network host \
           --name paca-business ${{ secrets.DOCKERHUB_USERNAME }}/paca-business:latest
-          docker logs paca-business
+          if [ $? -ne 0 ]; then
+            echo "Docker container exited with error"
+            echo "Check log file for more information: /app/project_runner.log"
+          else
+            echo "Docker container exited successfully"
+          fi
